### ISSUE TITLE
Procédure de démarrage

### ISSUE THREAD

**Issue by kevinvennitti** [erasme/evolyon#17]
Le README n'est pas à jour : quelle est la procédure pour rendre le dispositif fonctionnel ? Comment lancer oostidebox-client et index en même temps ? Sur quels ports se connecter avec le mobile et avec l'ordi ?

**Comment by clemsos** [comment]
550d899 résoud le problème.

En gros, il suffit d'allumer l'ordi est d'aller sur http://localhost:5000

Hier, j'ai ajouté le script dans `/etc/init.d/evolyon` et `update.rc`, ce qui veut dire que le script devrait se lancer tout seul au démarrage.

**Comment by kevinvennitti** [comment]
La raison ?

![img_20160324_142222](https://cloud.githubusercontent.com/assets/9624530/14018089/0dac9d94-f1cc-11e5-8fed-77d860a1ff0d.jpg)

**Comment by clemsos** [comment]
oui ? 
le script est bien lancé grâce au logiciel [forever](https://github.com/foreverjs/forever). 
Pour voir l'état du script, tu tapes forever list dans le terminal.

**Comment by clemsos** [comment]
est-ce que tu as qq chose à localhost:3000 ou 3010?

**Comment by clemsos** [comment]
Pour débuger, regarde les logs qui doivent se trouver dans ../log/ootsidebix.error.log . 

Il est possible que le port 3000 soit déjà occupé car le script se lance automatiquement au démarrage, ce qui t'empecherai par exemple de le lancer avec `./evolyon start`.  

Le script de démarrage est lancé en sudo. Fait un `sudo forever list` pour voir si des process sont en cours. Si tu veux killer tous les process en cours, fait `sudo forever kill 0`

**Comment by clemsos** [comment]
En espérant que ça t'aides !

**Comment by kevinvennitti** [comment]
Lorsque je lance `./evolyon start`, ça m'affiche ces lignes : 
![img_20160324_153530](https://cloud.githubusercontent.com/assets/9624530/14020252/a01f4a00-f1d6-11e5-8c1c-ec445debc1d9.jpg)

Et le `forever list` me dit qu'aucun process n'est en cours. Rien sur http://localhost:3000.

**Comment by clemsos** [comment]
Les lignes c'est normal. Essaye en sudo

**Comment by kevinvennitti** [comment]
Ok. Quand je lance en `sudo ./evolyon start`, ça fonctionne. Apparemment, le script exécuté automatiquement ne le fait pas en `sudo`, c'est pourquoi ça ne tournait pas. Je retrouve par contre le souci de n'avoir aucune gestuelle prise en compte et l'impossibilité de récupérer une particule avec un mobile.

Je suis dessus en croisant les logs pour détecter le souci, donc je change d'issue.

**Comment by clemsos** [comment]
Pour les gestes :

Verifie que le port sur lequel la ootside box est connectée correspond à celui renseigné dans le config.js

Tu peux vérifier le port avec les commandes  lsusb  ou dmesg | tail 

Si tu dois modifier le config.js, redémarre avec sudo ./evolyon restart

**Comment by kevinvennitti** [comment]
À priori, rien n'a été débranché/rebranché donc le port devrait encore correspondre. Dans `config.js`, le serial est à `/dev/ttyACM0` et je ne vois pas à quoi faire correspondre les valeurs de `lsusb`et ce ttyACM*.

**Comment by clemsos** [comment]
Oui a priori cela devrait marcher si rien n'a été débranché. L'idée est que `lsusb` va te montrer si un arduino est branché. Ensuite il faut regarder [dmesg](https://fr.wikipedia.org/wiki/Dmesg) pour savoir le /dev/ttyACM\* . 

Plus simplement, si tu fais `ls /dev/ttyACM0`, est-ce que ça fonctionne ?

Sinon, le meilleur moyen est de regarder au dos de la projection en haut à droite. Il y a un debug qui devrait afficher si les gestures sont reconnus ou pas.
