### ISSUE TITLE
Redis connection failed

### ISSUE THREAD

**Issue by kevinvennitti** [erasme/evolyon#19]
Le fichier de log `ootsidebox.error.js` m'annonce :

![29-03-2016 11 19 26 - terminal](https://cloud.githubusercontent.com/assets/9624530/14103427/6ba7c4a0-f5a0-11e5-85ee-32b92f48db50.png)

Faut-il lancer un `redis-server` sur le serveur lab.erasme.org ? Ou dans un sous-répertoire ?

**Comment by Pilooz** [comment]
Il semble qu'il s'agisse d'un redis-server sur lab.erasme.org dans le message d'erreur.
Tu peux le lancer aussi en local sur la machine si ce serveur est lié uniquement à une install mono machine, et ne partage rien avec personne ailleurs. Mais faudra re paramétrer dans le code.

**Comment by clemsos** [comment]
@kevinvennitti est-ce que tu étais connecté au web ? Il faut une connection web .
Redis assure le lien entre la machine locale sur l'install et le site web afin de faire marcher la collection de cellule via mobile. 

@Pilooz J'avais fait une install redis sur lab.erasme.org port 6379,  mais en effet on peut utiliser n'importe quel redis pour cela. Pour changer, il suffit de modifier le config.js https://github.com/erasme/evolyon/blob/master/config.js.example.js

**Comment by kevinvennitti** [comment]
@clemsos L'ordinateur est bien connecté au web. À chaque fois que je reboot l'ordinateur, j'obtiens la même erreur. le souci ne viendrait pas de la connexion Redis qui se fait automatiquement au boot mais avant que la connexion web soit OK ?

**Comment by clemsos** [comment]
possiblement. si tu fais `sudo ./evolyon restart` tu as aussi l'erreur ?

**Comment by kevinvennitti** [comment]
L'erreur ne se reproduit pas lorsque je `sudo ./evolyon restart`, uniquement lorsque je reboote. Cependant, si c'est lié, je suppose que : puisque la connexion foire au boot, il n'est pas possible de la relancer et donc le crash altère le `restart`.

![29-03-2016 14 08 28 - google chrome](https://cloud.githubusercontent.com/assets/9624530/14107369/0b439ff4-f5b8-11e5-8330-69644b67d2da.png)

Je tente de désactiver le lancement auto de ton script au boot pour le faire à la main ?

**Comment by clemsos** [comment]
ce que tu m'envoies me semble ok. il ya qqchose dans sudo forever list ?

**Comment by clemsos** [comment]
l'erreur redis devrais empêcher l'app de démarrer je pense

**Comment by kevinvennitti** [comment]
![29-03-2016 14 14 27 - terminal](https://cloud.githubusercontent.com/assets/9624530/14107455/944633fc-f5b8-11e5-8453-46b96267320d.png)

**Comment by clemsos** [comment]
ok donc ça marche ?

**Comment by kevinvennitti** [comment]
Nope.

Dans les logs, lorsque je tente un appui long sur mobile sur `lab.erasme.org:3000` et que je place ma main devant le 3Dpad, les logs `ootsidebox.out.log` me donnent `presence { presence: true }` puis `presence { presence: false }` sans ligne intermédiaire.

**Comment by clemsos** [comment]
attends, un par un. redis : ça marche ? depuis la machine tu fais `$ redis-cli  -h lab.erasme.org -p 6379` puis tu tapes `ping` dans l'invite de commande redis

ça devrait donner 

```
lab.erasme.org:6379> ping
PONG
```

**Comment by kevinvennitti** [comment]
Redis : ok, ça fonctionne

**Comment by clemsos** [comment]
ouvre une issue pour l'autre alors
