### ISSUE TITLE
On ne peut pas récupérer une particule avec son mobile + pas de gestuelle de génération des particules

### ISSUE THREAD

**Issue by kevinvennitti** [erasme/evolyon#20]
Les gestuelles face au 3Dpad ne créent rien et l'interaction `abribus > mobile` ne fonctionne pas non plus.

Questions :
- Est-ce qu'une limite maximale de particules est imposée dans le code ?
- Au lancement de `localhost:3010/cells`, j'ai un amas de particules (triangle + rect + sphère) de 3x10 entités (d'où ma question précédente) : recevrait-il un signal erroné une fois un nouvel user socket lui forçant à générer 30 entités ?

**Comment by kevinvennitti** [comment]
@MAKIO135 est passé voir, il pourra faire son compte-rendu ici sur ce qu'il identifie comme problème.

À priori, le souci vient de l'envoi des données du 3Dpad sur le serveur :
- Le 3Dpad envoie bien des données en serial (contrôlé via la console Arduino)
- Aucune donnée n'est envoyée sur le serveur donc aucune n'est récupérée par le client

@clemsos : @pvincent4 peut te procurer des accès à distance au serveur + machine locale si besoin. On a une échéance pour lundi 4 (midi) donc si tu as une disponibilité avant, ce serait top. Si tu as un créneau d'ici lundi matin (aujourd'hui ou demain), je peux aussi être tes mains sur la machine locale, et on échange via Skype / téléphone.

**Comment by kevinvennitti** [comment]
L'erreur précise se trouve ici, dans `log/ootsidebox.error.log` :

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to lab.erasme.org:6379 failed - getaddrinfo EAI_AGAIN lab.erasme.org:63$
    at Object.exports._errnoException (util.js:890:11)
    at errnoException (dns.js:31:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

```

**Comment by clemsos** [comment]
A priori `EAI_AGAIN` est une erreur passagère, donc il faut simplement rééssayer. Ca peut également être lié à un proxy sur le réseau. Est-ce que la connexion se fait derrière un proxy ?

http://github.com/npm/npm/issues/7348#issuecomment-74102087

**Comment by clemsos** [comment]
Sinon, je suis à Paris jusqu'à Dimanche. On peut s'appeler si tu veux

**Comment by clemsos** [comment]
Qu'affiche le log qui est derrière l'écran ?

**Comment by kevinvennitti** [comment]
À chaque tentative depuis 3 jours, la même erreur `EAI_AGAIN` s'affiche.
J'ai installé `fab` pour gérer la partie serveur (très pratique). 
- Je suppose qu'il suffit d'un `fab prod deploy` pour que tout soit configuré OK sur le serveur c'est ça ? Parce que lab.erasme.org:3000 ou lab.erasme.org:3010 ne répondent plus
- Peux-tu me décrire la démarche pour configurer le serveur Redis pour constater s'il est actif ou non ?

**Comment by clemsos** [comment]
Apparement le serveur était arrêté, donc en fait il faut faire un `fab start`. Ca tourne sur http://lab.erasme.org:3000 maintenant

Je t'ai mis les scripts de deploiement avec un settings.py à jour
- `lab` est le nom  du serveur lab.erasme.org, 
- le local/ootsidebox s'appelle `zotac`  

Pour redis, regarde  https://github.com/erasme/evolyon/issues/19#issuecomment-202882133

Dis-moi ce que ça donne

**Comment by kevinvennitti** [comment]
Ok, tout fonctionne grâce à l'aide de @MAKIO135. 
@clemsos, sur le Zotac, le `sudo ./evolyon start` lance `ootside.js` et `index.js` alors que `ìndex.js` n'a pas besoin d'être lancé en local (et causait sans doute le _ADDRINUSE_). Du coup, @MAKIO135 a cleané les processus côté serveur et a relancé via `fab lab deploy` côté serveur. La procédure de démarrage côté client est donc `cd www/evolyon/evolyon/ootsidebox-client && node ootside.js` :)
